version: "3.8"
services:
    api:
        build:
            context: ./
            target: dev
        container_name: api
        ports:
            - 8000:8000
        links:
            - mongo
        environment:
            - MONGO_URI=mongodb://user:password@mongo:27017/lf?authSource=admin
            - PORT=8000
            - FRONTEND_URL=http://localhost:3000
        volumes:
            - ./src:/app/src
        command: npm run start:dev
    mongo:
        image: mongo:6.0
        container_name: mongo
        command: mongod --auth
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
