version: "3.8"
services:
    api:
        build:
            context: ./
            target: dev
        container_name: api
        ports:
            - 8000:8000
        links:
            - mongo
        environment:
            - PORT=8000
            - MONGO_URI=mongodb://user:password@mongo:27017/lf?authSource=admin
            - POSTGRES_URI=postgres://user:password@postgres:5432/matches
            - FRONTEND_URL=http://localhost:3000
        volumes:
            - ./src:/app/src
        command: npm run start:dev
        depends_on:
            - mongo
            - postgres
    mongo:
        image: mongo:6.0
        container_name: mongo
        command: mongod --auth
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./tests/data:/data/db
    postgres:
        image: postgres:15.0
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=matches
