version: "3.8"
services:
    api:
        build:
            context: ./
            target: ${BUILD_TARGET:-dev}
        container_name: api
        ports:
            - 8000:8000
        links:
            - mongo
        environment:
            - PORT=8000
            - MONGO_URI=mongodb://user:password@mongo:27017/lf?authSource=admin
            - MATCHES_URI=postgres://user:password@matches:5432/matches
            - CONFIG_URI=postgres://user:password@config:5432/config
            - FRONTEND_URL=http://localhost:5173
            - MATCHER_URL=http://matcher:5000
            - AMQP_ENDPOINT=amqp://guest:guest@rabbitmq:5672
            - STREAM_CHAT_API_KEY=smqmafukudwa
            - STREAM_CHAT_SECRET=x4dryurjjjzsxcv6xeu2qjndm2zyway6rc7uvn8qsn57p4xwun2gh3t558kmx69t
        volumes:
            - ./src:/app/src
        depends_on:
            - mongo
            - matches
            - config
            - rabbitmq
        networks:
            - lf-dev

    mongo:
        image: mongo:6.0
        container_name: mongo
        command: mongod --auth
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data/items:/data/db
        networks:
            - lf-dev

    matches:
        image: postgres:15.0
        container_name: matches
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=matches
        volumes:
            - ./data/matches:/data/db
        networks:
            - lf-dev

    config:
        image: postgres:15.0
        container_name: config
        restart: always
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=config
        volumes:
            - ./data/config:/data/db
        networks:
            - lf-dev

    rabbitmq:
        image: rabbitmq:3.11-alpine
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        networks:
            - lf-dev

networks:
    lf-dev:
        name: lf-dev
        driver: bridge
